name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Setup OCaml
        run: |
          sudo apt-get -y update
          sudo apt-get -y install ocaml ocaml-dune ocaml-odoc libgraphics-ocaml-dev libx11-dev

      - name: Build
        run: dune build

      - name: Test
        run: dune runtest

      - name: Build documentation
        run: dune build @doc

      - name: Set-up pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/default/_doc/_html

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
